#!/bin/bash
#!/dona/dona/com.termux/files/usr/bin/bash

#Warna // Color
blue='\e[0;34m'
cyan='\e[0;36m'
okegreen='\033[92m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'

echo -e "$yellow Tool Under Maintenance :)"
echo  " Reload Tool on 22:00"
echo  " Thanks"

function reload(){
    curl -O https://raw.githubusercontent.com/loopstr34k/Dwipantara/master/dwipantarav024
    curl -O https://raw.githubusercontent.com/loopstr34k/Dwipantara/master/updone.sh
    sleep 1
    source dwipantarav024
}
help (){
clear
echo -e "$yellow Tool Under Maintenance :)"
echo " Reload Tool on 22:00"
echo " Thanks"
echo " Command :
                 reload      : Reload Script"

}
function ?()
{
clear
echo -e "$yellow Tool Under Maintenance :)"
echo " Reload Tool on 22:00"
echo " Thanks"
echo " Command :
                 reload      : Reload Script"
}
show_tool(){
clear
echo -e "$yellow Tool Under Maintenance :)"
echo " Reload Tool on 22:00"
echo " Thanks"
echo " Command :
                 reload      : Reload Script"
}
back(){
clear
echo -e "$yellow Tool Under Maintenance :)"
echo " Reload Tool on 22:00"
echo " Thanks"
echo " Command :
                 reload      : Reload Script"
}
version(){
clear
echo -e "$blue Version Tool is 0.2.4 $white"
echo -e "$yellow Tool Under Maintenance :)"
echo " Reload Tool on 22:00"
echo " Thanks"
echo " Command :
                 reload      : Reload Script"
}
contact() {
clear
echo " "
echo -e $red      "         [ Contact Author ]"
echo " "
echo -e $okegreen "     Author 1   ▶    MR.R3DH3T"
echo -e $okegreen "     Instagram  ▶    naufalziidane_"
echo -e $red      "------------------------------------------------"
echo -e $lightgreen     "     Author 2   ▶    LOOPSTR34K"
echo -e $lightgreen     "     Instagram  ▶    loopstr34k $white"
echo ""
echo -e "$yellow Tool Under Maintenance :)"
echo " Reload Tool on 22:00"
echo " Thanks"
}
function install(){
clear
echo -e "$yellow Tool Under Maintenance :)"
echo " Reload Tool on 22:00"
echo " Thanks"
echo " Command :
                 reload      : Reload Script"

}
function argument(){
read -p " Dwipantara : > " dwipantara;
for i in $dwipantara;do
     $i
done;
}
while :
do
argument $dwipantara
done
